=== MajorTom4711/ProfiSounder/config_schema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="sounderConfig" type="sounderConfig"/>

  <xs:complexType name="sounderConfig">
    <xs:sequence>
      <xs:element name="switchStateProvider" type="providerWrapper"/>
      <xs:element name="switch" type="switch" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="defaultSampleRate" type="xs:int"/>
  </xs:complexType>

  <xs:complexType name="providerWrapper">
    <xs:sequence>
      <xs:choice minOccurs="0">
        <xs:element name="netPoller" type="switchStateNetPoller"/>
        <xs:element name="gpioProvider" type="rpiGPIOStateProvider"/>
        <xs:element name="gpioProviderNoRoot" type="rpiGPIOStateProviderNoRoot"/>
        <xs:element name="netPollerOld" type="switchStateNetPollerOldMethod"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="switchStateNetPoller">
    <xs:complexContent>
      <xs:extension base="abstractSwitchStateProvider">
        <xs:sequence/>
        <xs:attribute name="profiluxAddress" type="xs:string" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="abstractSwitchStateProvider" abstract="true">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="rpiGPIOStateProvider">
    <xs:complexContent>
      <xs:extension base="abstractSwitchStateProvider">
        <xs:sequence>
          <xs:element name="switchMapping" type="switchMapping" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="switchMapping">
    <xs:sequence/>
    <xs:attribute name="switchNumber" type="xs:int" use="required"/>
    <xs:attribute name="rpiPin" type="xs:int" use="required"/>
    <xs:attribute name="rpiPinFeedbackHigh" type="xs:int"/>
    <xs:attribute name="pullUp" type="xs:boolean"/>
  </xs:complexType>

  <xs:complexType name="rpiGPIOStateProviderNoRoot">
    <xs:complexContent>
      <xs:extension base="abstractSwitchStateProvider">
        <xs:sequence>
          <xs:element name="switchMapping" type="switchMapping" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="switchStateNetPollerOldMethod">
    <xs:complexContent>
      <xs:extension base="abstractSwitchStateProvider">
        <xs:sequence/>
        <xs:attribute name="profiluxAddress" type="xs:string" use="required"/>
        <xs:attribute name="switchGroup" type="switchGroup"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="switch">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="onStateIs" type="onStateIs"/>
        <xs:element name="onStateChanged" type="onStateChanged"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="switchNumber" type="xs:int" use="required"/>
    <xs:attribute name="order" type="xs:int"/>
    <xs:attribute name="samplingRateLow" type="xs:int"/>
    <xs:attribute name="samplingRateHigh" type="xs:int"/>
  </xs:complexType>

  <xs:complexType name="onStateIs">
    <xs:complexContent>
      <xs:extension base="StateChange">
        <xs:sequence/>
        <xs:attribute name="currentState" type="currentState"/>
        <xs:attribute name="checkStateAtStartup" type="xs:boolean"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="StateChange" abstract="true">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="setVolumeSound" type="setVolumeSound"/>
        <xs:element name="setVolumeSwitch" type="setVolumeSwitch"/>
        <xs:element name="playSound" type="playSound"/>
        <xs:element name="stopSound" type="stopSound"/>
        <xs:element name="stopSwitchSounds" type="stopSwitch"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="oneOfAction" type="xs:boolean"/>
    <xs:attribute name="skipActionIfActive" type="xs:boolean"/>
  </xs:complexType>

  <xs:complexType name="setVolumeSound">
    <xs:sequence/>
    <xs:attribute name="soundFile" type="xs:string" use="required"/>
    <xs:attribute name="volume" type="xs:float" use="required"/>
    <xs:attribute name="fadeDuration" type="xs:int"/>
  </xs:complexType>

  <xs:complexType name="setVolumeSwitch">
    <xs:sequence/>
    <xs:attribute name="volume" type="xs:float" use="required"/>
    <xs:attribute name="switchNumber" type="xs:int" use="required"/>
    <xs:attribute name="fadeDuration" type="xs:int"/>
  </xs:complexType>

  <xs:complexType name="playSound">
    <xs:sequence/>
    <xs:attribute name="soundFile" type="xs:string" use="required"/>
    <xs:attribute name="fadeInDuration" type="xs:int"/>
    <xs:attribute name="loopCount" type="xs:int"/>
    <xs:attribute name="volume" type="xs:float"/>
  </xs:complexType>

  <xs:complexType name="stopSound">
    <xs:sequence/>
    <xs:attribute name="soundFile" type="xs:string" use="required"/>
    <xs:attribute name="fadeOutDuration" type="xs:int"/>
  </xs:complexType>

  <xs:complexType name="stopSwitch">
    <xs:sequence/>
    <xs:attribute name="switchNumber" type="xs:int" use="required"/>
    <xs:attribute name="fadeOutDuration" type="xs:int"/>
  </xs:complexType>

  <xs:complexType name="onStateChanged">
    <xs:complexContent>
      <xs:extension base="StateChange">
        <xs:sequence/>
        <xs:attribute name="durationFromMS" type="xs:int"/>
        <xs:attribute name="durationToMS" type="xs:int"/>
        <xs:attribute name="previousState" type="previousState"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="switchGroup">
    <xs:restriction base="xs:string">
      <xs:enumeration value="S1_S24"/>
      <xs:enumeration value="S25_S49"/>
      <xs:enumeration value="S50_S74"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="currentState">
    <xs:restriction base="xs:string">
      <xs:enumeration value="LOW"/>
      <xs:enumeration value="HIGH"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="previousState">
    <xs:restriction base="xs:string">
      <xs:enumeration value="LOW"/>
      <xs:enumeration value="HIGH"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== MajorTom4711/ProfiSounder/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"  ?>
<sounderConfig defaultSampleRate="5000" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config_schema.xsd">
	<switchStateProvider>
		<netPollerOld profiluxAddress="http://192.168.0.200" />
	</switchStateProvider>
	<switch samplingRateHigh="500" switchNumber="1">
		<onStateChanged previousState="LOW">
			<setVolumeSwitch fadeDuration="40000" switchNumber="3" volume="0.6" />
		</onStateChanged>
		<onStateChanged previousState="HIGH">
			<setVolumeSwitch fadeDuration="40000" switchNumber="3" volume="0.1" />
		</onStateChanged>
	</switch>
	<switch switchNumber="2">
		<onStateChanged previousState="HIGH" durationToMS="3000" oneOfAction="true">
			<playSound soundFile="sounds/Thunder_04.wav" />
			<playSound soundFile="sounds/Thunder_04_01.wav" />
			<playSound soundFile="sounds/Thunder_05.wav" />
			<playSound soundFile="sounds/Thunder_06.wav" />
			<playSound soundFile="sounds/Thunder_06_01.wav" />
			<playSound soundFile="sounds/Thunder_07.wav" />
			<playSound soundFile="sounds/Thunder_07_01.wav" />
			<playSound soundFile="sounds/Thunder_07_02.wav" />
			<playSound soundFile="sounds/Thunder_08.wav" />
			<playSound soundFile="sounds/Thunder_08_01.wav" />
			<playSound soundFile="sounds/Thunder_09.wav" />
			<playSound soundFile="sounds/Thunder_09_01.wav" />
			<playSound soundFile="sounds/Thunder_09_02.wav" />
			<playSound soundFile="sounds/Thunder_10.wav" />
			<playSound soundFile="sounds/Thunder_11.wav" />
			<playSound soundFile="sounds/Thunder_11_01.wav" />
			<playSound soundFile="sounds/Thunder_12.wav" />
		</onStateChanged>
		<onStateChanged previousState="HIGH" durationFromMS="3000" oneOfAction="true">
			<playSound soundFile="sounds/Thunder_13.wav" />
			<playSound soundFile="sounds/Thunder_13_01.wav" />
			<playSound soundFile="sounds/Thunder_13_02.wav" />
			<playSound soundFile="sounds/Thunder_15.wav" />
			<playSound soundFile="sounds/Thunder_15_01.wav" />
			<playSound soundFile="sounds/Thunder_16.wav" />
			<playSound soundFile="sounds/Thunder_19.wav" />
			<playSound soundFile="sounds/Thunder_25.wav" />
		</onStateChanged>
	</switch>
	<switch switchNumber="3">
		<onStateIs currentState="HIGH" skipActionIfActive="false">
			<playSound fadeInDuration="60000" loopCount="-1" volume="0.1" soundFile="sounds/Rain.mp3" />
		</onStateIs>
		<onStateIs currentState="LOW" skipActionIfActive="false">
			<stopSwitchSounds fadeOutDuration="60000" switchNumber="3" />
		</onStateIs>
	</switch>
</sounderConfig>
